version: '3.5'

services:
  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    restart: always
    ports:
      - '8203:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - "{{ grafana_deploy_dir }}/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "{{ grafana_dashboards_dir }}:/var/lib/grafana/dashboards"
      - "{{ grafana_datasources_dir }}:/etc/grafana/provisioning/datasources"
volumes:
  grafana_data: