---

- include_tasks: fetch_token.yml

- name: Add secret
  uri:
    url: "{{ vault_creds }}/v1/secrets/data/{{ vault_secret_path }}"
    method: POST
    body: "{'data':{{ vault_secret }}}"
    body_format: json
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
      X-Vault-Request: true
      Content-Type: application/json
  become: true