---
- name: Add secret
  uri:
    url: http://{{ vault_host }}:{{ vault_port }}/v1/secrets/data/{{ vault_secret_path }}
    method: POST
    body: "{'data':{{ vault_secret }}}"
    body_format: json
    headers:
      X-Vault-Token: "{{ vault_token }}"
      X-Vault-Request: true
      Content-Type: application/json
  become: true