---
- name: Get secret
  block:
  - uri:
      url: http://{{ vault_host }}:{{ vault_port }}/v1/secrets/data/{{ vault_secret_path }}
      method: GET
      headers:
        X-Vault-Token: "{{ vault_token }}"
    register: secret
    become: true
  rescue:
  - set_fact:
      get_secret_fail: true

- name: Return secret
  set_fact:
    return_secret: "{{ secret.json.data.data}}"
  when: secret.status != 404 and secret.status != 403 