version: "3.5"

services:
  jupyterhub:
    image: jupyterhub/jupyterhub
    volumes:
      - "{{ jupyterhub_deploy_dir }}/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      -  8000:8000
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py