user_passwds = [{% for pass in user_passwds pass + ","}]

Vagrant.configure("2") do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.provision "shell",
    master.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    master.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1", auto_correct: true
    master.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1", auto_correct: true
    master.vm.network "jupyternet", ip: "{{ vagrant_network }}.11", hostname: true
    master.ssh.username = "{{ defualt_user }}"
    master.ssh.password = user_pass[1]
    master.vm.provision "shell", inline: <<-SHELL
        apt update
        apt upgrade
        apt install -y docker.io docker-compose
        apt install wget curl htop
        swapoff -a
        SHELL
end

for i in 2..5 do
    config.vm.define "node-#{i}" do |slave|
        slave.vm.box = "ubuntu/jammy64"
        slave.vm.provision "shell",
        slave.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.customize ["modifyvm", :id, "--cpus", "1"]
            vb.customize ["modifyvm", :id, "--ioapic", "on"]
        end
        slave.vm.network "jupyternet", ip: "{{ vagrant_network }}.1#{i}", hostname: true
        slave.ssh.username = "{{ defualt_user }}"
        slave.ssh.password = user_pass[i]
        slave.vm.provision "shell", inline: <<-SHELL
            apt update
            apt upgrade
            apt install -y docker.io docker-compose
            apt install wget curl htop
            swapoff -a
            SHELL
    end
end