---
- name: Start prometheus
  ansible.builtin.import_role:
    name: docker_stack
  vars:
    - docker_stack_action: deploy
    - docker_stack_service_deploy_dir: "{{ prometheus_deploy_dir }}"
    - docker_stack_service_name: prometheus